### ISSUE TITLE
Debugging workflow

### ISSUE THREAD

**Issue by bensyverson** [lvsti/CoreMediaIO-DAL-Example#12]
First, thank you so much @lvsti for this repo—it has saved me a huge amount of time and is greatly appreciated! I have a hopefully simple question: how do I debug the Assistant?

I noticed a hook in `CMIO_DPA_Sample_VCamServer.cpp` to wait for the debugger. However, when I run the Assistant from Xcode, it exits with code 43... The call to `bootstrap_check_in` fails with error 1100 (`BOOTSTRAP_NOT_PRIVILEGED`).

From what I can understand, that's because the plugin actually has to initialize the port (?) with `bootstrap_create_server`. But I'm a bit stuck as to how to invoke the plugin from Xcode. Any hints would be so helpful.

Thanks again!

**Comment by lvsti** [comment]
Hi, to be honest I don't remember how (or whether) I did it back at the time, but perhaps the "Debugging Tips" section in the [Core_Media_IO_DAL_Example.pdf](https://github.com/lvsti/CoreMediaIO-DAL-Example/blob/master/Documentation/Core%20Media%20IO%20DAL%20Example.pdf) contains some hints.
