### ISSUE TITLE
[Question] Possible to output a html5 page/canvas to a virtual webcam 

### ISSUE THREAD

**Issue by bomanden** [lvsti/CoreMediaIO-DAL-Example#14]
Hi 
Been trying to find something that can output an electron app to a virtual webcam 
(osx-coreMediaIO / windows-directx). 
Would it be possible with this example or similar, can see you did quite a few virtual webcam projects.

**Comment by lvsti** [comment]
Hi,
I'm not familiar with the possibilities in an electron app, but if you can capture the pixels in your app window then you can definitely feed that into a virtual webcam, e.g. by using IOSurface via XPC. This example is not prepared for receiving images via XPC but it wouldn't be too hard to extend it.

**Comment by bomanden** [comment]
Thanks alot, for the inputs. 
I think I would need to write some kind of c++ plugin for electron. that could receive the pixels from html canvas object, then pass that on to what you describe. 
I'll try to investigate 'IOSurface via XPC' :) , thanks.

**Comment by Raj123456788** [comment]
@bomanden : Did you figure out the C++ plugin? I would appreciate if you can guide me. Docs 7 examples are appreciated Thanks!
