### ISSUE TITLE
Example to send the buffers outside the plugin

### ISSUE THREAD

**Issue by Raj123456788** [lvsti/CoreMediaIO-DAL-Example#16]
Hello,
I have asked almost every repository about this. The ones that implement this do not compile due to various reasons.
Is there any way you can tell me an example that is able to send the buffer outside the sample?

**Comment by lvsti** [comment]
Hi, what exactly do you want to achieve? The plugin already "sends" the buffer through CMIO to camera consumers, aren't you rather interested in _receiving_ a buffer in the plugin?

**Comment by Raj123456788** [comment]
Yes, That is what I meant? I am writing a C++ program to upload the samplebuffer to the plugin. Is there an example?

**Comment by Raj123456788** [comment]
@lvsti: Any update with receiving buffer in the plugin?

**Comment by lvsti** [comment]
Take a look at these:

http://www.russbishop.net/cross-process-rendering
https://stackoverflow.com/questions/42721360/encoding-h-264-compression-session-with-cgdisplaystream

or just google the 3 magic keywords: "cmsamplebuffer iosurface xpc"

**Comment by Raj123456788** [comment]
How to run the sample assistants? Not sure how they are helpful.

**Comment by sivrish** [comment]
@lvsti If I'm not wrong the assistant is creating a bootstrap mach server and from our vcam mac app we have to connect to that and send the frames to it and it'll deliver the frames to the camera apps like photo booth, zoom etc.. ? If I'm right about the first part can you tell me where I can find code sample to connect to the assistant from my mac app ? been searching about this for more than 10 days, new to mac dev. Thanks in advance.

**Comment by lvsti** [comment]
@sivrish indeed it is setting up a bootstrap server but I'd recommend against using that in your code. Bootstrap has been deprecated in favor of XPC services, so you should take a look at those instead. E.g. this is a good starting point: https://www.objc.io/issues/14-mac/xpc/ , afterwards check out the links in my previous post.
