### ISSUE TITLE
I'm only getting empty output

### ISSUE THREAD

**Issue by acrosson** [lvsti/CoreMediaIO-DAL-Example#8]
Thanks for putting this and the Cameo tool together!

I think I have setup the virtual camera correctly. When I open your cameo app, I am able to see the virtual device, and "open it". However when I view the output it's all green. In PhotoBooth the output is always black. So I'm not sure if it's working properly or not. Is there anyway to send random noise for the frame in EmitFrame?

Also, whenever I switch to another device and back to the virtual device, whichever app i'm using crashes. Any suggestions?

Thanks!!

**Comment by johnboiles** [comment]
It's probably because you don't have the `.yuv` files downloaded. See my comment [here](https://github.com/lvsti/CoreMediaIO-DAL-Example/issues/7#issuecomment-604585476)

**Comment by lvsti** [comment]
@acrosson did it solve your problem?

**Comment by acrosson** [comment]
@lvsti yes, got it working now! Thanks
